name:                flake-to-gitlab-ci
version:             0.1.0.0
git:                 "githubuser/flake-to-gitlab-ci"
license:             MIT
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/flake-to-gitlab-ci#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- containers
- formatting
- lens
- lens-aeson
- shh
- text
- vector
- yaml

default-extensions:
- GHC2021

library:
  source-dirs: src

executables:
  flake-to-gitlab-ci-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - flake-to-gitlab-ci
